/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/module1/': RouteRecordInfo<'/module1/', '/module1', Record<never, never>, Record<never, never>>,
    '/module1/child-module/test': RouteRecordInfo<'/module1/child-module/test', '/module1/child-module/test', Record<never, never>, Record<never, never>>,
    '/module2/': RouteRecordInfo<'/module2/', '/module2', Record<never, never>, Record<never, never>>,
  }
}
