/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/_internal/login': RouteRecordInfo<'/_internal/login', '/_internal/login', Record<never, never>, Record<never, never>>,
    '/_internal/login2': RouteRecordInfo<'/_internal/login2', '/_internal/login2', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/modules/module1/': RouteRecordInfo<'/modules/module1/', '/modules/module1', Record<never, never>, Record<never, never>>,
    '/modules/module1/child-module/test': RouteRecordInfo<'/modules/module1/child-module/test', '/modules/module1/child-module/test', Record<never, never>, Record<never, never>>,
    '/modules/module2/': RouteRecordInfo<'/modules/module2/', '/modules/module2', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/worker': RouteRecordInfo<'/worker', '/worker', Record<never, never>, Record<never, never>>,
  }
}
